services:
  # Application Web NestJS
  - type: web
    name: tp-secu-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        fromDatabase:
          name: tp-secu-db
          property: connectionString

# Base de données MongoDB
databases:
  - name: tp-secu-db
    databaseName: tp_secu
    plan: free 